Don't set pipefail for apt-update script to keep it simple

diff --git a/scripts/bin/apt-update b/scripts/bin/apt-update
--- a/scripts/bin/apt-update
+++ b/scripts/bin/apt-update
@@ -3,10 +3,10 @@
 # Quick script to handle upgrading Debian based systems
 
 # A better class of script...
-set -o errexit  # Exit on most errors (see the manual)
-set -o errtrace # Make sure any error trap is inherited
-set -o pipefail # Exit on failures earlier in a pipeline
-#set -o xtrace  # Trace the execution of the script (debug)
+set -o errexit          # Exit on most errors (see the manual)
+set -o errtrace         # Make sure any error trap is inherited
+#set -o pipefail        # Exit on failures earlier in a pipeline
+#set -o xtrace          # Trace the execution of the script (debug)
 
 if ! sudo -v 2> /dev/null; then
     echo 'This script requires sudo access.'
