Now with parameter support & sensible defaults

diff --git a/scripts/bin/dot-update b/scripts/bin/dot-update
--- a/scripts/bin/dot-update
+++ b/scripts/bin/dot-update
@@ -8,21 +8,54 @@ set -o errtrace         # Make sure any error trap is inherited
 set -o pipefail         # Exit on failures earlier in a pipeline
 #set -o xtrace          # Trace the execution of the script (debug)
 
-orig_dir="$PWD"
-script_dir="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
-dotfiles_dir="$(cd "$script_dir"; git rev-parse --show-toplevel)"
+function script_init() {
+    orig_dir="$PWD"
+    script_dir="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
+    dotfiles_dir="$(cd "$script_dir"; git rev-parse --show-toplevel)"
+}
 
-echo '*** Updating Git sources...'
-cd "$dotfiles_dir"
-git fetch
-git merge --ff-only
-git submodule init
-git submodule update
+function parse_params() {
+    if [[ $# -eq 0 ]]; then
+        git_update=true
+    else
+        while [[ $# -gt 0 ]]; do
+            param="$1"
+            shift
+            case $param in
+                -h|--help)
+                    echo 'Usage: [-h|--help] [-g|--git] [-v|--vim]'
+                    exit 0
+                    ;;
+                -g|--git)
+                    git_update=true
+                    ;;
+                -v|--vim)
+                    vim_update=true
+                    ;;
+                *)
+                    echo "Invalid parameter was provided: $param"
+                    exit 1
+            esac
+        done
+    fi
+}
 
-echo -e "\n*** Updating Vim bundles..."
-vim +PluginUpdate +qall
+script_init
+parse_params $@
 
-cd "$orig_dir"
-echo -e "\n*** Done!"
+if [[ -n $git_update ]]; then
+    echo '*** Updating Git sources...'
+    cd "$dotfiles_dir"
+    git fetch
+    git merge --ff-only
+    git submodule init
+    git submodule update
+    cd "$orig_dir"
+fi
+
+if [[ -n $vim_update ]]; then
+    echo '*** Updating Vim bundles...'
+    vim +PluginUpdate +qall
+fi
 
 # vim: syntax=sh cc=80 tw=79 ts=4 sw=4 sts=4 et sr
